# Copyright 2026 Zyvor AI Labs · https://zyvor.dev
# SPDX-License-Identifier: Apache-2.0
FROM golang:1.27.1-alpine@sha256:8a5910f31396cd4d89662f56c68b3ae31d374308270a1c3bd96672ee5ed43414 AS gobuild
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY api/ api/
COPY cmd/haven-controller/ cmd/haven-controller/
COPY internal/ internal/
RUN CGO_ENABLED=0 go build -o /out/haven-controller ./cmd/haven-controller

FROM gcr.io/distroless/static-debian13:nonroot@sha256:e2e927ec666bae08560abb3c55d0659eceabb657f56b6782ab500a9fc7f555e3
COPY --from=gobuild /out/haven-controller /haven-controller
USER nonroot:nonroot
ENTRYPOINT ["/haven-controller"]
