apiVersion: v1
kind: Namespace
metadata:
  name: identity
  labels:
    haven.identity/managed: "true"
    app.kubernetes.io/part-of: haven
---
apiVersion: identity.haven.dev/v1alpha1
kind: IdentityPlane
metadata:
  name: platform
  namespace: identity
  labels:
    haven.identity/profile: dev
spec:
  profile: dev
  hostname: auth.127.0.0.1.nip.io
  consoleHostname: haven.127.0.0.1.nip.io
  database:
    vendor: postgres
    instances: 1
    storage: 8Gi
  keycloak:
    instances: 1
    version: "26.8.0"
    features:
      - persistent-user-sessions
    resources:
      requests:
        cpu: "500m"
        memory: 768Mi
      limits:
        cpu: "2"
        memory: 1536Mi
  expose:
    class: ingress
    networkPolicy: false
  bootstrap:
    adminEmail: admin@local.dev
    firstRealm: platform
    clients:
      - name: haven-console
        type: public
        redirects:
          - https://haven.127.0.0.1.nip.io/*
      - name: kubernetes
        type: confidential
        audiences:
          - https://kubernetes.default.svc
  observability:
    metrics: true
    tracing: false
